# Generated by Django 4.0.1 on 2022-01-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_variationvalue'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product_variationvalue',
            managers=[
            ],
        ),
    ]
