# Generated by Django 4.0.1 on 2022-02-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_bannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
