# Generated by Django 4.0.1 on 2022-02-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_color_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Paypal', 'Paypal'), ('SSLcommerz', 'SSLcommerz')], default='Cash on Delivery', max_length=50),
        ),
    ]
